# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainMemoryPerformanceWindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

from PySide2extn.RoundProgressBar import roundProgressBar


class Ui_MainmemoryPerformanceWindow(object):
    def setupUi(self, MainmemoryPerformanceWindow):
        if not MainmemoryPerformanceWindow.objectName():
            MainmemoryPerformanceWindow.setObjectName(u"MainmemoryPerformanceWindow")
        MainmemoryPerformanceWindow.resize(800, 568)
        self.centralwidget = QWidget(MainmemoryPerformanceWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 10, 331, 31))
        font = QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.sysnodename_txt_2 = QLabel(self.centralwidget)
        self.sysnodename_txt_2.setObjectName(u"sysnodename_txt_2")
        self.sysnodename_txt_2.setGeometry(QRect(50, 60, 261, 21))
        font1 = QFont()
        font1.setPointSize(10)
        self.sysnodename_txt_2.setFont(font1)
        self.sysnodename_txt = QLabel(self.centralwidget)
        self.sysnodename_txt.setObjectName(u"sysnodename_txt")
        self.sysnodename_txt.setGeometry(QRect(10, 440, 301, 21))
        self.sysnodename_txt.setFont(font1)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 470, 191, 21))
        self.label_11.setFont(font1)
        self.memory_usage_progress = roundProgressBar(self.centralwidget)
        self.memory_usage_progress.setObjectName(u"memory_usage_progress")
        self.memory_usage_progress.setGeometry(QRect(10, 90, 341, 331))
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 500, 141, 21))
        self.label_12.setFont(font1)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(390, 60, 401, 461))
        font2 = QFont()
        font2.setPointSize(12)
        self.groupBox.setFont(font2)
        self.label_22 = QLabel(self.groupBox)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 70, 191, 21))
        self.label_22.setFont(font1)
        self.label_23 = QLabel(self.groupBox)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 100, 211, 21))
        self.label_23.setFont(font1)
        self.label_24 = QLabel(self.groupBox)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 30, 381, 21))
        self.label_24.setFont(font1)
        self.totmem_txt = QLabel(self.groupBox)
        self.totmem_txt.setObjectName(u"totmem_txt")
        self.totmem_txt.setGeometry(QRect(260, 70, 91, 21))
        self.totmem_txt.setFont(font1)
        self.usedmem_txt = QLabel(self.groupBox)
        self.usedmem_txt.setObjectName(u"usedmem_txt")
        self.usedmem_txt.setGeometry(QRect(260, 100, 91, 21))
        self.usedmem_txt.setFont(font1)
        self.label_25 = QLabel(self.groupBox)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 130, 241, 21))
        self.label_25.setFont(font1)
        self.freespacemem_txt = QLabel(self.groupBox)
        self.freespacemem_txt.setObjectName(u"freespacemem_txt")
        self.freespacemem_txt.setGeometry(QRect(260, 130, 91, 21))
        self.freespacemem_txt.setFont(font1)
        self.label_26 = QLabel(self.groupBox)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 160, 241, 21))
        self.label_26.setFont(font1)
        self.percentagemem_txt = QLabel(self.groupBox)
        self.percentagemem_txt.setObjectName(u"percentagemem_txt")
        self.percentagemem_txt.setGeometry(QRect(260, 160, 91, 21))
        self.percentagemem_txt.setFont(font1)
        self.swaptot_txt = QLabel(self.groupBox)
        self.swaptot_txt.setObjectName(u"swaptot_txt")
        self.swaptot_txt.setGeometry(QRect(260, 240, 91, 21))
        self.swaptot_txt.setFont(font1)
        self.label_27 = QLabel(self.groupBox)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 240, 191, 21))
        self.label_27.setFont(font1)
        self.swappercentage_txt = QLabel(self.groupBox)
        self.swappercentage_txt.setObjectName(u"swappercentage_txt")
        self.swappercentage_txt.setGeometry(QRect(260, 330, 91, 21))
        self.swappercentage_txt.setFont(font1)
        self.label_28 = QLabel(self.groupBox)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 300, 241, 21))
        self.label_28.setFont(font1)
        self.label_29 = QLabel(self.groupBox)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 270, 211, 21))
        self.label_29.setFont(font1)
        self.label_30 = QLabel(self.groupBox)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 200, 381, 21))
        self.label_30.setFont(font1)
        self.swapfree_txt = QLabel(self.groupBox)
        self.swapfree_txt.setObjectName(u"swapfree_txt")
        self.swapfree_txt.setGeometry(QRect(260, 300, 91, 21))
        self.swapfree_txt.setFont(font1)
        self.label_31 = QLabel(self.groupBox)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 330, 241, 21))
        self.label_31.setFont(font1)
        self.swapused_txt = QLabel(self.groupBox)
        self.swapused_txt.setObjectName(u"swapused_txt")
        self.swapused_txt.setGeometry(QRect(260, 270, 91, 21))
        self.swapused_txt.setFont(font1)
        MainmemoryPerformanceWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainmemoryPerformanceWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 21))
        MainmemoryPerformanceWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainmemoryPerformanceWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainmemoryPerformanceWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainmemoryPerformanceWindow)

        QMetaObject.connectSlotsByName(MainmemoryPerformanceWindow)
    # setupUi

    def retranslateUi(self, MainmemoryPerformanceWindow):
        MainmemoryPerformanceWindow.setWindowTitle(QCoreApplication.translate("MainmemoryPerformanceWindow", u"MainWindow", None))
        self.label_7.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"System Primary Memory Informations", None))
        self.sysnodename_txt_2.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"System Primary memory Usage Percentage", None))
        self.sysnodename_txt.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"...", None))
        self.label_11.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"Current Memory Usage Percentage :- ", None))
        self.label_12.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"Time Frame (s) :- ", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainmemoryPerformanceWindow", u"Primary Memory General Informations", None))
        self.label_22.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"Total Primary Memory Space :- ", None))
        self.label_23.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"Total Used Primary Memory Space :- ", None))
        self.label_24.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"================Surface Details ================", None))
        self.totmem_txt.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"...", None))
        self.usedmem_txt.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"...", None))
        self.label_25.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"Total Free Space In Primary memory :- ", None))
        self.freespacemem_txt.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"...", None))
        self.label_26.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"Percentage Of Main Memory :- ", None))
        self.percentagemem_txt.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"...", None))
        self.swaptot_txt.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"...", None))
        self.label_27.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"Total Swap Memory Space :- ", None))
        self.swappercentage_txt.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"...", None))
        self.label_28.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"Total Free Space In Swap memory :- ", None))
        self.label_29.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"Total Used Swap Memory Space :- ", None))
        self.label_30.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"================Swap memory Details ================", None))
        self.swapfree_txt.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"...", None))
        self.label_31.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"Percentage Of Swap Memory :- ", None))
        self.swapused_txt.setText(QCoreApplication.translate("MainmemoryPerformanceWindow", u"...", None))
    # retranslateUi

