# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'performance.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

from PySide2extn.RoundProgressBar import roundProgressBar


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1401, 760)
        MainWindow.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.actionGo_to_our_web_site = QAction(MainWindow)
        self.actionGo_to_our_web_site.setObjectName(u"actionGo_to_our_web_site")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionStart_Disk_Defragmentation = QAction(MainWindow)
        self.actionStart_Disk_Defragmentation.setObjectName(u"actionStart_Disk_Defragmentation")
        self.actionCheck_Disk_Health = QAction(MainWindow)
        self.actionCheck_Disk_Health.setObjectName(u"actionCheck_Disk_Health")
        self.actionGet_Volume_Informations = QAction(MainWindow)
        self.actionGet_Volume_Informations.setObjectName(u"actionGet_Volume_Informations")
        self.actionGet_System_Informations = QAction(MainWindow)
        self.actionGet_System_Informations.setObjectName(u"actionGet_System_Informations")
        self.actionProcessor_Performance = QAction(MainWindow)
        self.actionProcessor_Performance.setObjectName(u"actionProcessor_Performance")
        self.actionMemory_Performance = QAction(MainWindow)
        self.actionMemory_Performance.setObjectName(u"actionMemory_Performance")
        self.actionStorage_Status_Informations = QAction(MainWindow)
        self.actionStorage_Status_Informations.setObjectName(u"actionStorage_Status_Informations")
        self.actionNetwork_Informations = QAction(MainWindow)
        self.actionNetwork_Informations.setObjectName(u"actionNetwork_Informations")
        self.actionCurrent_Running_Processes = QAction(MainWindow)
        self.actionCurrent_Running_Processes.setObjectName(u"actionCurrent_Running_Processes")
        self.actionClean_Browser_Cache = QAction(MainWindow)
        self.actionClean_Browser_Cache.setObjectName(u"actionClean_Browser_Cache")
        self.actionClean_RAM_Cache = QAction(MainWindow)
        self.actionClean_RAM_Cache.setObjectName(u"actionClean_RAM_Cache")
        self.actionDisk_Clean_UP = QAction(MainWindow)
        self.actionDisk_Clean_UP.setObjectName(u"actionDisk_Clean_UP")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionHow_To = QAction(MainWindow)
        self.actionHow_To.setObjectName(u"actionHow_To")
        self.actionClean_Disk = QAction(MainWindow)
        self.actionClean_Disk.setObjectName(u"actionClean_Disk")
        self.actionClean_Disk_2 = QAction(MainWindow)
        self.actionClean_Disk_2.setObjectName(u"actionClean_Disk_2")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(330, 20, 21, 761))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 10, 281, 31))
        font = QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 60, 101, 21))
        font1 = QFont()
        font1.setPointSize(10)
        self.label_2.setFont(font1)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 90, 111, 21))
        self.label_3.setFont(font1)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 120, 71, 21))
        self.label_4.setFont(font1)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 150, 71, 21))
        self.label_5.setFont(font1)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 180, 81, 21))
        self.label_6.setFont(font1)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 230, 321, 441))
        self.groupBox.setFont(font)
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 50, 181, 31))
        self.label_8.setFont(font1)
        self.drive_list_cmb = QComboBox(self.groupBox)
        self.drive_list_cmb.setObjectName(u"drive_list_cmb")
        self.drive_list_cmb.setGeometry(QRect(190, 51, 121, 31))
        self.drive_list_cmb.setFont(font1)
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 100, 161, 21))
        self.label_9.setFont(font1)
        self.freespace_progress = QProgressBar(self.groupBox)
        self.freespace_progress.setObjectName(u"freespace_progress")
        self.freespace_progress.setGeometry(QRect(10, 130, 301, 41))
        self.freespace_progress.setValue(24)
        self.label_10 = QLabel(self.groupBox)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 180, 141, 21))
        self.label_10.setFont(font1)
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 210, 161, 21))
        self.label_11.setFont(font1)
        self.label_12 = QLabel(self.groupBox)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 240, 191, 21))
        self.label_12.setFont(font1)
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 310, 191, 21))
        self.label_13.setFont(font1)
        self.line_2 = QFrame(self.groupBox)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(17, 280, 291, 20))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.selecteddrive_txt = QLabel(self.groupBox)
        self.selecteddrive_txt.setObjectName(u"selecteddrive_txt")
        self.selecteddrive_txt.setGeometry(QRect(170, 100, 131, 21))
        self.selecteddrive_txt.setFont(font1)
        self.pushButton = QPushButton(self.groupBox)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 390, 301, 31))
        font2 = QFont()
        font2.setPointSize(12)
        self.pushButton.setFont(font2)
        self.totalspace_txt = QLabel(self.groupBox)
        self.totalspace_txt.setObjectName(u"totalspace_txt")
        self.totalspace_txt.setGeometry(QRect(210, 180, 91, 21))
        self.totalspace_txt.setFont(font1)
        self.usedspace_txt = QLabel(self.groupBox)
        self.usedspace_txt.setObjectName(u"usedspace_txt")
        self.usedspace_txt.setGeometry(QRect(210, 210, 81, 21))
        self.usedspace_txt.setFont(font1)
        self.freespace_txt = QLabel(self.groupBox)
        self.freespace_txt.setObjectName(u"freespace_txt")
        self.freespace_txt.setGeometry(QRect(210, 240, 91, 21))
        self.freespace_txt.setFont(font1)
        self.volumetype_txt = QLabel(self.groupBox)
        self.volumetype_txt.setObjectName(u"volumetype_txt")
        self.volumetype_txt.setGeometry(QRect(110, 310, 91, 21))
        self.volumetype_txt.setFont(font1)
        self.processor_txt = QLabel(self.groupBox)
        self.processor_txt.setObjectName(u"processor_txt")
        self.processor_txt.setGeometry(QRect(110, 340, 171, 21))
        self.processor_txt.setFont(font1)
        self.label_14 = QLabel(self.groupBox)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 340, 191, 21))
        self.label_14.setFont(font1)
        self.sysname_txt = QLabel(self.centralwidget)
        self.sysname_txt.setObjectName(u"sysname_txt")
        self.sysname_txt.setGeometry(QRect(120, 60, 101, 21))
        self.sysname_txt.setFont(font1)
        self.nodename_txt = QLabel(self.centralwidget)
        self.nodename_txt.setObjectName(u"nodename_txt")
        self.nodename_txt.setGeometry(QRect(120, 90, 151, 21))
        self.nodename_txt.setFont(font1)
        self.release_txt = QLabel(self.centralwidget)
        self.release_txt.setObjectName(u"release_txt")
        self.release_txt.setGeometry(QRect(120, 120, 101, 21))
        self.release_txt.setFont(font1)
        self.version_txt = QLabel(self.centralwidget)
        self.version_txt.setObjectName(u"version_txt")
        self.version_txt.setGeometry(QRect(120, 150, 101, 21))
        self.version_txt.setFont(font1)
        self.machine_txt = QLabel(self.centralwidget)
        self.machine_txt.setObjectName(u"machine_txt")
        self.machine_txt.setGeometry(QRect(120, 180, 101, 21))
        self.machine_txt.setFont(font1)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(360, 10, 281, 31))
        self.label_7.setFont(font)
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(360, 210, 201, 21))
        self.label_15.setFont(font1)
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(360, 130, 171, 21))
        self.label_16.setFont(font1)
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(360, 170, 191, 21))
        self.label_17.setFont(font1)
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(1180, 190, 191, 21))
        self.label_18.setFont(font1)
        self.label_20 = QLabel(self.centralwidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(1180, 150, 161, 21))
        self.label_20.setFont(font1)
        self.diskfreespace_txt = QLabel(self.centralwidget)
        self.diskfreespace_txt.setObjectName(u"diskfreespace_txt")
        self.diskfreespace_txt.setGeometry(QRect(560, 210, 91, 21))
        self.diskfreespace_txt.setFont(font1)
        self.diskusedspace_txt = QLabel(self.centralwidget)
        self.diskusedspace_txt.setObjectName(u"diskusedspace_txt")
        self.diskusedspace_txt.setGeometry(QRect(560, 170, 81, 21))
        self.diskusedspace_txt.setFont(font1)
        self.disktotalspace_txt = QLabel(self.centralwidget)
        self.disktotalspace_txt.setObjectName(u"disktotalspace_txt")
        self.disktotalspace_txt.setGeometry(QRect(560, 130, 91, 21))
        self.disktotalspace_txt.setFont(font1)
        self.usedspace_lab = QLabel(self.centralwidget)
        self.usedspace_lab.setObjectName(u"usedspace_lab")
        self.usedspace_lab.setGeometry(QRect(1130, 190, 21, 21))
        self.usedspace_lab.setFont(font1)
        self.totlab_txt = QLabel(self.centralwidget)
        self.totlab_txt.setObjectName(u"totlab_txt")
        self.totlab_txt.setGeometry(QRect(1130, 150, 21, 21))
        self.totlab_txt.setFont(font1)
        self.diskstorage_progress = roundProgressBar(self.centralwidget)
        self.diskstorage_progress.setObjectName(u"diskstorage_progress")
        self.diskstorage_progress.setGeometry(QRect(640, 70, 231, 211))
        self.diskstorage_progress2 = roundProgressBar(self.centralwidget)
        self.diskstorage_progress2.setObjectName(u"diskstorage_progress2")
        self.diskstorage_progress2.setGeometry(QRect(880, 70, 231, 211))
        self.nodename_txt2 = QLabel(self.centralwidget)
        self.nodename_txt2.setObjectName(u"nodename_txt2")
        self.nodename_txt2.setGeometry(QRect(780, 20, 181, 21))
        self.nodename_txt2.setFont(font1)
        self.label_21 = QLabel(self.centralwidget)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(650, 20, 141, 21))
        self.label_21.setFont(font1)
        self.label_22 = QLabel(self.centralwidget)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(360, 300, 521, 31))
        self.label_22.setFont(font)
        self.gridLayoutWidget = QWidget(self.centralwidget)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(360, 349, 991, 321))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(390, 70, 231, 21))
        self.label_19.setFont(font1)
        self.label_23 = QLabel(self.centralwidget)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(1120, 70, 231, 21))
        self.label_23.setFont(font1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1401, 21))
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuTools = QMenu(self.menuBar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuPerformance = QMenu(self.menuBar)
        self.menuPerformance.setObjectName(u"menuPerformance")
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuPerformance.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionGo_to_our_web_site)
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionClean_Disk_2)
        self.menuTools.addAction(self.actionStart_Disk_Defragmentation)
        self.menuTools.addAction(self.actionCheck_Disk_Health)
        self.menuTools.addAction(self.actionGet_Volume_Informations)
        self.menuPerformance.addAction(self.actionProcessor_Performance)
        self.menuPerformance.addAction(self.actionMemory_Performance)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionHow_To)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionGo_to_our_web_site.setText(QCoreApplication.translate("MainWindow", u"Go to our web site", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit ", None))
        self.actionStart_Disk_Defragmentation.setText(QCoreApplication.translate("MainWindow", u"Start Disk Defragmentation", None))
        self.actionCheck_Disk_Health.setText(QCoreApplication.translate("MainWindow", u"Check Disk Health", None))
        self.actionGet_Volume_Informations.setText(QCoreApplication.translate("MainWindow", u"Get Volume Informations", None))
        self.actionGet_System_Informations.setText(QCoreApplication.translate("MainWindow", u"Get System Informations", None))
        self.actionProcessor_Performance.setText(QCoreApplication.translate("MainWindow", u"Processor Performance", None))
        self.actionMemory_Performance.setText(QCoreApplication.translate("MainWindow", u"Memory Performance", None))
        self.actionStorage_Status_Informations.setText(QCoreApplication.translate("MainWindow", u"Storage Status Informations", None))
        self.actionNetwork_Informations.setText(QCoreApplication.translate("MainWindow", u"Network Informations", None))
        self.actionCurrent_Running_Processes.setText(QCoreApplication.translate("MainWindow", u"Current Running Processes", None))
        self.actionClean_Browser_Cache.setText(QCoreApplication.translate("MainWindow", u"Clean Browser Cache", None))
        self.actionClean_RAM_Cache.setText(QCoreApplication.translate("MainWindow", u"Clean RAM Cache", None))
        self.actionDisk_Clean_UP.setText(QCoreApplication.translate("MainWindow", u"Disk Clean UP", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionHow_To.setText(QCoreApplication.translate("MainWindow", u"How To", None))
        self.actionClean_Disk.setText(QCoreApplication.translate("MainWindow", u"Clean Disk", None))
        self.actionClean_Disk_2.setText(QCoreApplication.translate("MainWindow", u"Clean Disk", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Operating System Informations", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Sys name :- ", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Node Name :- ", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Release :- ", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Version :- ", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Machine :- ", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Volume Informations", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Choose Your Volume Letter :- ", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Selected Volume Name :- ", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Total Volume Space :- ", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Total Used Volume Space :- ", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Total Available Volume Space :- ", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Volume Type :- ", None))
        self.selecteddrive_txt.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Refresh Volume List", None))
        self.totalspace_txt.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.usedspace_txt.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.freespace_txt.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.volumetype_txt.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.processor_txt.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Processor :- ", None))
        self.sysname_txt.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.nodename_txt.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.release_txt.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.version_txt.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.machine_txt.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"System Disk Informations Status", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Total Available Disk Space :- ", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Total Internal Disk Space :- ", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Total Used Internal Disk Space :- ", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Total Available Volume Space", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Total Used Volume Space", None))
        self.diskfreespace_txt.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.diskusedspace_txt.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.disktotalspace_txt.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.usedspace_lab.setText("")
        self.totlab_txt.setText("")
        self.nodename_txt2.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Host name (Node) :- ", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Processor tempreture and Performance Line Chart Statictics", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Percentage For Total Used Disk Space", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Percentage For Total Free Disk Space", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuPerformance.setTitle(QCoreApplication.translate("MainWindow", u"Performance", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
    # retranslateUi

