# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ProcessorInformationsWindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

from PySide2extn.RoundProgressBar import roundProgressBar


class Ui_ProcessorInformationWindow(object):
    def setupUi(self, ProcessorInformationWindow):
        if not ProcessorInformationWindow.objectName():
            ProcessorInformationWindow.setObjectName(u"ProcessorInformationWindow")
        ProcessorInformationWindow.resize(800, 600)
        self.centralwidget = QWidget(ProcessorInformationWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 10, 271, 31))
        font = QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.cpu_usage_progress = roundProgressBar(self.centralwidget)
        self.cpu_usage_progress.setObjectName(u"cpu_usage_progress")
        self.cpu_usage_progress.setGeometry(QRect(20, 100, 341, 331))
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(389, 49, 401, 491))
        font1 = QFont()
        font1.setPointSize(12)
        self.groupBox.setFont(font1)
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 160, 191, 21))
        font2 = QFont()
        font2.setPointSize(10)
        self.label_13.setFont(font2)
        self.label_14 = QLabel(self.groupBox)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 190, 171, 21))
        self.label_14.setFont(font2)
        self.label_15 = QLabel(self.groupBox)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 260, 171, 21))
        self.label_15.setFont(font2)
        self.label_16 = QLabel(self.groupBox)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 290, 171, 21))
        self.label_16.setFont(font2)
        self.label_17 = QLabel(self.groupBox)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 320, 171, 21))
        self.label_17.setFont(font2)
        self.label_19 = QLabel(self.groupBox)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 130, 381, 21))
        self.label_19.setFont(font2)
        self.label_20 = QLabel(self.groupBox)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 230, 381, 21))
        self.label_20.setFont(font2)
        self.label_21 = QLabel(self.groupBox)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 360, 381, 21))
        self.label_21.setFont(font2)
        self.label_22 = QLabel(self.groupBox)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 60, 171, 21))
        self.label_22.setFont(font2)
        self.label_23 = QLabel(self.groupBox)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 90, 121, 21))
        self.label_23.setFont(font2)
        self.label_24 = QLabel(self.groupBox)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 30, 381, 21))
        self.label_24.setFont(font2)
        self.physicalName_txt = QLabel(self.groupBox)
        self.physicalName_txt.setObjectName(u"physicalName_txt")
        self.physicalName_txt.setGeometry(QRect(180, 60, 171, 21))
        self.physicalName_txt.setFont(font2)
        self.machineName_txt = QLabel(self.groupBox)
        self.machineName_txt.setObjectName(u"machineName_txt")
        self.machineName_txt.setGeometry(QRect(180, 90, 171, 21))
        self.machineName_txt.setFont(font2)
        self.physicalCores_txt = QLabel(self.groupBox)
        self.physicalCores_txt.setObjectName(u"physicalCores_txt")
        self.physicalCores_txt.setGeometry(QRect(190, 160, 171, 21))
        self.physicalCores_txt.setFont(font2)
        self.totalCores_txt = QLabel(self.groupBox)
        self.totalCores_txt.setObjectName(u"totalCores_txt")
        self.totalCores_txt.setGeometry(QRect(190, 190, 201, 21))
        self.totalCores_txt.setFont(font2)
        self.maxFrequency_txt = QLabel(self.groupBox)
        self.maxFrequency_txt.setObjectName(u"maxFrequency_txt")
        self.maxFrequency_txt.setGeometry(QRect(150, 260, 171, 21))
        self.maxFrequency_txt.setFont(font2)
        self.minFrequency_txt = QLabel(self.groupBox)
        self.minFrequency_txt.setObjectName(u"minFrequency_txt")
        self.minFrequency_txt.setGeometry(QRect(150, 290, 171, 21))
        self.minFrequency_txt.setFont(font2)
        self.currentFrequency_txt = QLabel(self.groupBox)
        self.currentFrequency_txt.setObjectName(u"currentFrequency_txt")
        self.currentFrequency_txt.setGeometry(QRect(150, 320, 171, 21))
        self.currentFrequency_txt.setFont(font2)
        self.gridLayoutWidget = QWidget(self.groupBox)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(10, 390, 381, 80))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.sysnodename_txt = QLabel(self.centralwidget)
        self.sysnodename_txt.setObjectName(u"sysnodename_txt")
        self.sysnodename_txt.setGeometry(QRect(20, 450, 301, 21))
        self.sysnodename_txt.setFont(font2)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 480, 191, 21))
        self.label_11.setFont(font2)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 510, 141, 21))
        self.label_12.setFont(font2)
        self.sysnodename_txt_2 = QLabel(self.centralwidget)
        self.sysnodename_txt_2.setObjectName(u"sysnodename_txt_2")
        self.sysnodename_txt_2.setGeometry(QRect(90, 70, 221, 21))
        self.sysnodename_txt_2.setFont(font2)
        self.usedspace_lab = QLabel(self.centralwidget)
        self.usedspace_lab.setObjectName(u"usedspace_lab")
        self.usedspace_lab.setGeometry(QRect(220, 510, 21, 21))
        self.usedspace_lab.setFont(font2)
        self.totlab_txt = QLabel(self.centralwidget)
        self.totlab_txt.setObjectName(u"totlab_txt")
        self.totlab_txt.setGeometry(QRect(220, 480, 21, 21))
        self.totlab_txt.setFont(font2)
        ProcessorInformationWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(ProcessorInformationWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 21))
        ProcessorInformationWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(ProcessorInformationWindow)
        self.statusbar.setObjectName(u"statusbar")
        ProcessorInformationWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ProcessorInformationWindow)

        QMetaObject.connectSlotsByName(ProcessorInformationWindow)
    # setupUi

    def retranslateUi(self, ProcessorInformationWindow):
        ProcessorInformationWindow.setWindowTitle(QCoreApplication.translate("ProcessorInformationWindow", u"MainWindow", None))
        self.label_7.setText(QCoreApplication.translate("ProcessorInformationWindow", u"System Processor Informations", None))
        self.groupBox.setTitle(QCoreApplication.translate("ProcessorInformationWindow", u"Processor General Informations", None))
        self.label_13.setText(QCoreApplication.translate("ProcessorInformationWindow", u"Physical Cores In Processor :- ", None))
        self.label_14.setText(QCoreApplication.translate("ProcessorInformationWindow", u"Total Cores In Processor :- ", None))
        self.label_15.setText(QCoreApplication.translate("ProcessorInformationWindow", u"Max Frequency :- ", None))
        self.label_16.setText(QCoreApplication.translate("ProcessorInformationWindow", u"Min Frequency :- ", None))
        self.label_17.setText(QCoreApplication.translate("ProcessorInformationWindow", u"Current Frequency :- ", None))
        self.label_19.setText(QCoreApplication.translate("ProcessorInformationWindow", u"================ Core Details ==================", None))
        self.label_20.setText(QCoreApplication.translate("ProcessorInformationWindow", u"=============== Frequency Details ===============", None))
        self.label_21.setText(QCoreApplication.translate("ProcessorInformationWindow", u"============= Usage Per Core Details ==============", None))
        self.label_22.setText(QCoreApplication.translate("ProcessorInformationWindow", u"Processor Physical Name :- ", None))
        self.label_23.setText(QCoreApplication.translate("ProcessorInformationWindow", u"Machine Name :- ", None))
        self.label_24.setText(QCoreApplication.translate("ProcessorInformationWindow", u"================Physical Details ================", None))
        self.physicalName_txt.setText(QCoreApplication.translate("ProcessorInformationWindow", u"...", None))
        self.machineName_txt.setText(QCoreApplication.translate("ProcessorInformationWindow", u"...", None))
        self.physicalCores_txt.setText(QCoreApplication.translate("ProcessorInformationWindow", u"...", None))
        self.totalCores_txt.setText(QCoreApplication.translate("ProcessorInformationWindow", u"...", None))
        self.maxFrequency_txt.setText(QCoreApplication.translate("ProcessorInformationWindow", u"...", None))
        self.minFrequency_txt.setText(QCoreApplication.translate("ProcessorInformationWindow", u"...", None))
        self.currentFrequency_txt.setText(QCoreApplication.translate("ProcessorInformationWindow", u"...", None))
        self.sysnodename_txt.setText(QCoreApplication.translate("ProcessorInformationWindow", u"...", None))
        self.label_11.setText(QCoreApplication.translate("ProcessorInformationWindow", u"Current CPU Usage Percentage :- ", None))
        self.label_12.setText(QCoreApplication.translate("ProcessorInformationWindow", u"Time Frame (s) :- ", None))
        self.sysnodename_txt_2.setText(QCoreApplication.translate("ProcessorInformationWindow", u"System processor Usage Percentage", None))
        self.usedspace_lab.setText("")
        self.totlab_txt.setText("")
    # retranslateUi

