# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'UsageWindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_UsageWindow(object):
    def setupUi(self, UsageWindow):
        if not UsageWindow.objectName():
            UsageWindow.setObjectName(u"UsageWindow")
        UsageWindow.resize(800, 600)
        self.centralwidget = QWidget(UsageWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 311, 31))
        font = QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 60, 311, 31))
        font1 = QFont()
        font1.setPointSize(10)
        self.label_2.setFont(font1)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(260, 70, 521, 20))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 100, 601, 31))
        self.label_3.setFont(font1)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 130, 711, 31))
        self.label_4.setFont(font1)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 160, 781, 31))
        self.label_5.setFont(font1)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 190, 711, 31))
        self.label_6.setFont(font1)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(210, 230, 571, 20))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 220, 311, 31))
        self.label_7.setFont(font1)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 250, 671, 31))
        self.label_8.setFont(font1)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(30, 280, 761, 31))
        self.label_9.setFont(font1)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 310, 801, 31))
        self.label_10.setFont(font1)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(50, 330, 181, 31))
        self.label_11.setFont(font1)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 360, 771, 31))
        self.label_12.setFont(font1)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(50, 380, 181, 31))
        self.label_13.setFont(font1)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(210, 420, 571, 20))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 410, 311, 31))
        self.label_14.setFont(font1)
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(30, 440, 761, 31))
        self.label_15.setFont(font1)
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(30, 500, 661, 31))
        self.label_16.setFont(font1)
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(30, 470, 661, 31))
        self.label_17.setFont(font1)
        UsageWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(UsageWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 21))
        UsageWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(UsageWindow)
        self.statusbar.setObjectName(u"statusbar")
        UsageWindow.setStatusBar(self.statusbar)

        self.retranslateUi(UsageWindow)

        QMetaObject.connectSlotsByName(UsageWindow)
    # setupUi

    def retranslateUi(self, UsageWindow):
        UsageWindow.setWindowTitle(QCoreApplication.translate("UsageWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("UsageWindow", u"Usage Of The Software Application", None))
        self.label_2.setText(QCoreApplication.translate("UsageWindow", u"Basic Usage Of The Software Application", None))
        self.label_3.setText(QCoreApplication.translate("UsageWindow", u"@. At first we can see software application dashboard and it shows the whole disk drive storage status.", None))
        self.label_4.setText(QCoreApplication.translate("UsageWindow", u"@. Below That Status,it shows Data plot in the line chart about processor performance.it shows live update in data ploting.", None))
        self.label_5.setText(QCoreApplication.translate("UsageWindow", u"@. And the left side of the software application it shows the operating system details (SysName,NodeName,machine etc.)", None))
        self.label_6.setText(QCoreApplication.translate("UsageWindow", u"@. Below the operating system details it displays all teh partitions brief details.", None))
        self.label_7.setText(QCoreApplication.translate("UsageWindow", u"Disk Performance Of the system", None))
        self.label_8.setText(QCoreApplication.translate("UsageWindow", u"@. In the tools section first the Disk CleanUP,it helps to Clean up your tempory files,system files,other varios files .", None))
        self.label_9.setText(QCoreApplication.translate("UsageWindow", u"@. In the tools Section after the Disk CleanUP it has Disk Defragmentation,This can defrag our Disk and make it better performance.", None))
        self.label_10.setText(QCoreApplication.translate("UsageWindow", u"@. In the Tools Section after the Disk Defragmentation it has Check Disk health, This can Check Our Hard Disk and fix", None))
        self.label_11.setText(QCoreApplication.translate("UsageWindow", u" various sector failures in Disk.", None))
        self.label_12.setText(QCoreApplication.translate("UsageWindow", u"@. In the tools section after the Check Disk health it has Volume Informations, in this sction you can see all the", None))
        self.label_13.setText(QCoreApplication.translate("UsageWindow", u" partion informations in details.", None))
        self.label_14.setText(QCoreApplication.translate("UsageWindow", u"Processor & RAM Performance", None))
        self.label_15.setText(QCoreApplication.translate("UsageWindow", u"@. In processor Performance Window,it shows the Processor's main core's average performance in left side Circular Progress Bar.", None))
        self.label_16.setText(QCoreApplication.translate("UsageWindow", u"@. In RAM Performance Window,it shows Main Memory Performance and SWAP Memory Performance.", None))
        self.label_17.setText(QCoreApplication.translate("UsageWindow", u"@. Also it shows other sub core's average performance value percentage.", None))
    # retranslateUi

